 platform :osx, '10.10'

target 'JProperty' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'ACEView', :git => 'https://github.com/mmattozzi/ACEView.git', :submodules => true
end
